version: "3"
services:
      mongo:
        container_name: mongo
        image: mongo
        restart: always
        ports:
         - "27017:27017"
        volumes:
         - /home/${USER}/mongo/data/db:/data/db
      backend:
        container_name: backend
        image: backendnew:v2       
        restart: always
        ports:
         - "5000:5000"
        links:
         - mongo      
        volumes:
         - ./:/home/node/app
      frontend:
        container_name: frontend
        image: frontend:v2
        restart: always
        volumes:
         - ./frontend:/app
        ports:
         - "3000:3000"
      mongo-express:
        image: mongo-express
        container_name: mongo-express
        links:
         - mongo      
        environment:
         - ME_CONFIG_MONGODB_URL="mongodb://mongo:27017"
        ports:
         - "8081:8081"
        volumes:
         - /home/${USER}/mongo/data/db:/data/db

